const actionType = {
  LOAD_DATA_COMPANY: 'LOAD_DATA_COMPANY',
  LOAD_DATA_COMPANY_SUCCESS: 'LOAD_DATA_COMPANY_SUCCESS',
  LOAD_DATA_COMPANY_FAILURE: 'LOAD_DATA_COMPANY_FAILURE',
};

export default actionType;
